### PR TITLE
DYN-7080 Updating IronPython2.7 package Description

### PR DESCRIPTION
**Pull request by RobertGlobant20**
### Purpose

Updating Description for IronPython2.7 package.
I was not able to test if the description was updated due that Dynamo is getting the data from the server, then first need to be published and then we will be able to test.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [X] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [X] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated
- [ ] This PR contains no files larger than 50 MB

### Release Notes

Updating Description for IronPython2.7 package.

### Reviewers
@QilongTang 
@mjkkirschner 
@pinzart90 
@jasonstratton 

### FYIs
@reddyashish

### CODE REVIEW

**Comment by QilongTang** [comment]
Requesting review from Turbo team

**Comment by RobertGlobant20** [comment]
@AlexisErazoGlobant could you review this changes?
Thanks

**Review by sm6srw — COMMENTED** [review]
Sorry that this took so long. Do we need to update the package version?

**Comment by QilongTang** [comment]
> Sorry that this took so long. Do we need to update the package version?

I think so, otherwise the package cant be re-published

**Review by sm6srw — APPROVED** [review]
LGTM

**Comment by sm6srw** [comment]
Please note that a package with signed binaries will be available in Jenkins [here](https://master-5.jenkins.autodesk.com/job/Dynamo/job/DSIronPython/job/master/) after merge (and sync).

**Pull request merged**
